# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6547698c7ca07e6a4700b124dbf9ca01eae9eadc4018f1e5898364c4170706266002e28cd1125e95f25ee6f8bf5d9a27ee13bb2a2a527328d7afebf110905f4

test:
  secret_key_base: 3d6a402a9cce95027a6f8408bd30920b766c85878cb0fc0eb57c37391487b540b5aca1b78ececb80580b0d7a7a118a3c6114a5aed01164d70143f8e30df1aaef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
